version: '3.8'

services:
  app:
    build:
      context: .
    container_name: symfony_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - symfony_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge

